// <auto-generated />
namespace eCommerce.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02AddedMonthlyPayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02AddedMonthlyPayment));
        
        string IMigrationMetadata.Id
        {
            get { return "201609082042177_02-Added-MonthlyPayment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
